import Head from "next/head"
import { ReactNode } from "react"
import Pagewrapper from "../pagewrapper"

interface LayoutsProps {
  children: ReactNode
}

export default function Layouts(props: LayoutsProps) {
  const { children } = props
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Pagewrapper>
        <div>{children}</div>
      </Pagewrapper>
    </>
  )
}
